// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dntajvuvqdiatxpdxpem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudGFqdnV2cWRpYXR4cGR4cGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzMzODksImV4cCI6MjA2NTc0OTM4OX0.WcXNHRB_m-XAWOLjfmmKfelNOHE1IGkMnAgv_VXKTr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);